name: CI for Terraform

on:
  pull_request:
    branches:
      - main  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.3  
        
    - name: Terraform init
      run: terraform init

    - name: Terraform fmt
      run: terraform fmt -check -recursive

    - name: Terraform validate
      run: terraform validate
